# Generated by Django 3.2.3 on 2021-06-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.CharField(default=941103, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(default=11111111111, max_length=11),
            preserve_default=False,
        ),
    ]
