# Generated by Django 3.2.3 on 2021-07-22 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClipperChapter",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "clipper_chapter",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClipperCourse",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                (
                    "thumbnail_link",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("instructor", models.CharField(blank=True, max_length=300, null=True)),
                ("course_link", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "clipper_course",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClipperSection",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "clipper_section",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClipperSite",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
            ],
            options={
                "db_table": "clipper_site",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MyCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.clippercourse",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
