# Generated by Django 3.2.3 on 2021-07-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_mycourse_site"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mycourse",
            old_name="course_info",
            new_name="course",
        ),
    ]
